spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  jpa:
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
security:
  encoding-strength: 256
  signing-key: MaYzkSjmkzPC57L
  security-realm: Grub2GoBackendApplication
  oauth2:
    resource:
      filter-order: 3