spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  data:
    rest:
      base-path: /api
  jpa:
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
